### ISSUE TITLE
Invalid or missing nodebanks

### ISSUE THREAD

**Issue by Gsuz** [blockworks-foundation/mango-client-v3#86]
I'm getting this error when trying to use method: client.settleFunds(mangoGroup, mangoAccount, owner, spotMarket);

/Users/borkur/Desktop/Coding/mango-client-v3/src/client.ts:2649
      throw new Error('Invalid or missing node banks');
            ^
Error: Invalid or missing node banks
    at MangoClient.<anonymous> (/Users/borkur/Desktop/Coding/mango-client-v3/src/client.ts:2649:13)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/borkur/Desktop/Coding/mango-client-v3/src/client.ts:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Triggsy22** [comment]
I got the same problem, but on client.cancelSpotOrder.
I solved it with:
`mangoGroup.loadRootBanks(connection);`
